services:
  - type: web
    name: bitacora-adr-mecal
    runtime: node
    buildCommand: npm install && npm rebuild sqlite3 && mkdir -p /opt/render/project/src/database
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: bitacora-disk
      mountPath: /opt/render/project/src/database
      sizeGB: 1
